### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Jbarget** [rt2zz/redux-persist-immutable#1]
Im getting a runtime error saying 'Cannot convert undefined or null to object'.
the error comes from a compiled function called `_toConsumableArray` thats only arguement is an array.

Could it be that you need to initialise `immutableTransform` with an empty object?

**Comment by rt2zz** [comment]
Needed to default transforms in case they come in undefined. 4.0.0-alpha2 out with the fix

**Comment by Jbarget** [comment]
ha thanks for this! im almost there i feel :) 
'transforms is not defined'

`transforms = [].concat(_toConsumableArray(incomingTransforms), [_reduxPersistTransformImmutable2.default]);`

**Comment by rt2zz** [comment]
:facepalm: completely my bad (I am trying to squeeze these fixes in on a train)

I published alpha3 with fix. No promises, but at the very least we are one step closer.

**Comment by Jbarget** [comment]
looking good now!
