### ISSUE TITLE
Allow passing props to immutableTransform

### ISSUE THREAD

**Issue by SvenC81** [rt2zz/redux-persist-immutable#10]
Would it be possible to allow parameters for the immutableTransform  transformer?
I'm working with Records and normalizr-immutable and need to pass Records and whitelist/blacklist some reducers.

**Comment by rt2zz** [comment]
the underlying Records can be handled by redux-persist-immutable-transform, so this should be doable by simply proxying through that config option into immutableTransform here: https://github.com/rt2zz/redux-persist-immutable/blob/master/src/index.js#L16

more context: https://github.com/rt2zz/redux-persist-transform-immutable#usage-with-records

If you can put together a PR I will gladly merge

**Comment by SvenC81** [comment]
Pull request: #14

**Comment by rt2zz** [comment]
Merged! I ended up tweaking it so you can pass in records directly instead of immutableTranformConfig. Seems like this is a good thing to have as a top level option.

**Comment by SvenC81** [comment]
Thanks, however I made it more generic to also be able to also pass whitelist & blacklist of store items not to serialise (eg plain values). Perhaps adding a second argument to pass those?
