### ISSUE TITLE
lib build files differ from master

### ISSUE THREAD

**Issue by fabriziomoscon** [rt2zz/redux-persist-immutable#30]
I noticed that this

```
var persistStore = function persistStore(store) ...
```

is different from what is on master

<img width="1176" alt="screen shot 2017-06-23 at 17 55 40" src="https://user-images.githubusercontent.com/721890/27492204-4de66402-583d-11e7-9991-f30000c6ee15.png">

Something might have gone bad with the prepublish npm command

cc @rt2zz

**Comment by rt2zz** [comment]
What ended up being the issue? Is a new publish required?

**Comment by fabriziomoscon** [comment]
Sorry,
False positive :)
